DROP DATABASE IF EXISTS enrolkodego;
CREATE DATABASE IF NOT EXISTS enrolkodego;
USE enrolkodego;
CREATE TABLE users(
	user_id INT AUTO_INCREMENT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(254) NOT NULL,
	datecreated DATETIME
		DEFAULT CURRENT_TIMESTAMP,
	dateupdated TIMESTAMP
		DEFAULT CURRENT_TIMESTAMP
		ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE courses(
	course_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	course_name VARCHAR(50) NOT NULL UNIQUE,
    course_description VARCHAR(50) NOT NULL UNIQUE,
	datecreated DATETIME
		DEFAULT CURRENT_TIMESTAMP,
	dateupdated TIMESTAMP
		DEFAULT CURRENT_TIMESTAMP
		ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE students(
	student_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
	course_id INT NOT NULL,
    datecreated DATETIME
		DEFAULT CURRENT_TIMESTAMP,
	dateupdated TIMESTAMP
		DEFAULT CURRENT_TIMESTAMP
		ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (course_id) REFERENCES courses(course_id) 
		ON DELETE restrict
        ON UPDATE cascade
);



